### ISSUE TITLE
Max data handling limit

### ISSUE THREAD

**Issue by arnabk** [infostreams/db#5]
We use oracle and have to handle image size of around 150gb. How practical is it to use this with oracle?

**Comment by infostreams** [comment]
Hey, sorry for the late reply - I was on holidays over the break. I did think about this question a bit though.

Your use case is an interesting one. I think the general structure of this tool (doing things like ```db save```, ```db load``` etc) would work with any kind of database, and I do think that it would be possible to write a connector to make these commands work with an Oracle database.

However, the image size of 150gb is probably an issue here. Taking inspiration from git, the tool basically stores the whole database dump into the repository. It does gzip them, but that's it. This approach generally simplifies follow-up operations, such as loading a specific dump back into the db, or only loading certain tables from a dump, but if your dump is 150gb (is that gzipped?) you might quickly run out of disk space. 

Not to mention that saving and loading dumps will probably hog your CPU for a long time (you can renice the dump/load process though, if you write the connector), and the current connector doesn't provide any feedback while saving and loading so it will look like the process hangs.

So, to answer your question: yes, I think you can make this work with large Oracle databases. It will probably make your life easier because creating and restoring dumps is more convenient. You will still have to deal with any side-effects of working with such large database images, such as CPU hogging and quickly running out of disk space.

I hope this answers your question. If you end up writing an Oracle adapter, feel free to share what you've created, however perfect or imperfect it might be.

**Comment by infostreams** [comment]
Hi, I will close this issue. Please re-open if the above reply does not sufficiently address your concerns.
